# Generated by Django 3.2.8 on 2021-11-04 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_curso', models.CharField(blank=True, max_length=100, null=True)),
                ('inicio_curso', models.DateTimeField(blank=True, null=True)),
                ('fin_curso', models.DateTimeField(blank=True, null=True)),
                ('documento', models.CharField(blank=True, max_length=20, null=True)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.persona')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
