# Generated by Django 3.2.8 on 2021-12-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='fin_curso',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='inicio_curso',
        ),
        migrations.AddField(
            model_name='cursos',
            name='horas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
