# Generated by Django 3.2.8 on 2021-12-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20211202_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='fecha_curso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
