# Generated by Django 3.2.8 on 2021-12-03 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_cursos_fecha_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='fecha_curso',
        ),
    ]
