# Generated by Django 3.2.8 on 2021-12-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_remove_cursos_fecha_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='horas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
