# Generated by Django 3.2.8 on 2021-11-04 00:25

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('adscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.adscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_puesto', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_rango', models.CharField(blank=True, max_length=255, null=True)),
                ('sueldo_bruto', models.CharField(blank=True, max_length=20, null=True)),
                ('sueldo_neto', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_administrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subdireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clavesp', models.CharField(blank=True, max_length=20, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('apaterno', models.CharField(max_length=255)),
                ('amaterno', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=10, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='persona/fotos')),
                ('num_plaza', models.CharField(blank=True, max_length=20, null=True)),
                ('cuip', models.CharField(blank=True, max_length=20, null=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('calle', models.CharField(blank=True, max_length=255, null=True)),
                ('interior', models.CharField(blank=True, max_length=10, null=True)),
                ('exterior', models.CharField(blank=True, max_length=10, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
                ('correo', models.EmailField(blank=True, max_length=50, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_familiar', models.CharField(blank=True, max_length=255, null=True)),
                ('nss', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_sangre', models.CharField(blank=True, max_length=5, null=True)),
                ('escolaridad', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('motivo_baja', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('adscripcion', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='unidad_administrativa', chained_model_field='unidad_administrativa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.adscripcion')),
                ('colonia', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='municipio', chained_model_field='municipio', null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.colonia')),
                ('departamento', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='subdireccion', chained_model_field='subdireccion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.departamento')),
                ('direccion', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='adscripcion', chained_model_field='adscripcion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.direccion')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.municipio')),
                ('puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.puesto')),
                ('subdireccion', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='direccion', chained_model_field='direccion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.subdireccion')),
                ('unidad_administrativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.unidad_administrativa')),
            ],
            options={
                'ordering': ['apaterno'],
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='subdireccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.subdireccion'),
        ),
        migrations.AddField(
            model_name='colonia',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.municipio'),
        ),
        migrations.AddField(
            model_name='adscripcion',
            name='unidad_administrativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.unidad_administrativa'),
        ),
    ]
