# Generated by Django 3.2.8 on 2021-12-03 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20211201_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['created']},
        ),
    ]
